### ISSUE TITLE
The sdist package of kurobako v0.1.2 doesn't match with github tag.

### ISSUE THREAD

**Issue by c-bata** [sile/kurobako-py#1]
The following change seems not to be included in sdist package of v0.1.2 on PyPI.

https://github.com/sile/kurobako-py/commit/92c71ec8c80b65442e4870fcf5b96f04bef53bd7

**Comment by sile** [comment]
Thank you for letting me know that. I just bumped up the package version to v0.1.3 and published it on PyPI.
